openapi: 3.1.0
x-stoplight:
  id: me8l2h1u3ej92
info:
  title: 20ref
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '306':
          description: (Unused)
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '404':
          description: User Not Found
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        1XX:
          description: Informational
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: 3gza7yuwxczni
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '404':
          description: User Not Found
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '409':
          description: Email Already Taken
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: dlce6kefir3ls
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '302':
          description: Found
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '400':
          description: Missing Required Information
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '409':
          description: Email Already Taken
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        1XX:
          description: Informational
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: ouytbjljvjl9h
  /four:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '203':
          description: Non-Authoritative Information
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '302':
          description: Found
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '303':
          description: See Other
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml?deref=bundle'
        '510':
          description: Not Extended
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        '598':
          description: Network read timeout error
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml?deref=bundle'
        1XX:
          description: Informational
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
        2XX:
          description: Success
          content:
            application/json:
              schema:
                $ref: 'https://stoplight.io/api/v1/projects/caitlin/designlibrary/nodes/models/mug.yaml'
      operationId: get-four
      x-stoplight:
        id: gwyqyscd5ucny
components:
  schemas:
    User:
      $ref: 'stoplight://resources/overrides/1QkT7j1bAWc'
      x-stoplight:
        id: n0eudv09fwioz
