openapi: 3.1.0
info:
  title: idk
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: string
                  next:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                        count:
                          type: string
                        Validator:
                          anyOf:
                            - $ref: '#/components/schemas/Validator'
                            - type: 'null'
                              properties: {}
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
    post:
      summary: ''
      operationId: post-users-userId
      responses:
        '200':
          description: OK
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /bm/catalog/product-validations/history:
    get:
      summary: List statistics of validation operations per operator and day in the given market.
      description: List statistics of validation operations per operator and day in the given market.
      x-tier: 3
      tags:
        - Products Validation
      operationId: get-bm-catalog-product-validations-history
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    example: 'https://www.backmarket.fr/bm/catalog/products-validation/history?marketCode=FR&page=2'
                    nullable: true
                  previous:
                    type: string
                    example: null
                    nullable: true
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          $ref: '#/components/schemas/FullDate'
                        countValidatedInMarket:
                          type: number
                          example: 3
                        countRematched:
                          type: number
                          example: 10
                        validator:
                          anyOf:
                            - $ref: '#/components/schemas/Validator'
                            - nullable: true
                              type: 'null'
                      required:
                        - date
                        - countValidatedInMarket
                        - countRematched
                        - validator
                required:
                  - count
                  - next
                  - previous
                  - results
        '401':
          description: Unauthenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseV2'
        '403':
          description: Forbidden.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseV2'
        '422':
          description: Unprocessable entity. Filters or pages are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseV2'
  /dogs:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  color:
                    type: string
                  id:
                    type: string
      operationId: get-dogs
      parameters:
        - schema:
            type: string
          in: query
          name: name
components:
  schemas:
    User:
      title: User
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      anyOf:
        - type: object
          properties:
            id:
              type: integer
              description: Unique identifier for the given user.
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
              format: email
            dateOfBirth:
              type: string
              format: date
              example: '1997-10-31'
            emailVerified:
              type: boolean
              description: Set to true if the user's email has been verified.
            createDate:
              type: string
              format: date
              description: The date that the user was created.
          required:
            - id
            - firstName
            - lastName
            - email
            - emailVerified
        - type: string
          properties: {}
    Validator:
      type: object
      required:
        - username
        - id
      properties:
        username:
          type: string
          example: john.doe.ext
        id:
          type: number
          example: 6634224
